apiVersion: v1
kind: PersistentVolume
metadata:
  name: device-conf-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/device_conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: device-conf-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
